[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"
[[headers]]

 for = "/*"
 [headers.values]
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   X-Content-Type-Options = "nosniff"
   Referrer-Policy= "no-referrer-when-downgrade"
   [[headers]]
  for = "*.png" # png files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
