baseurl = "https://suplementos.netlify.com/"
languageCode = "pt-br"
title = "Suplementos Blog"
[permalinks]
post = "/:title"
  # Nome Disqus
  disqusShortname = "SuplementosBlog"
  enableRobotsTXT = "true"
  [params]
description = "O blog que agrega em sua vida, com dicas importantes sobre suplementos e exercícios físicos."
keywords = "Suplementos, academia, treino, musculação"
[taxonomies]
author = "autores"
category = "categorias"
tag = "tags"
[sitemap]
  ChangeFreq = "daily"
  Priority = "1"
  filename = "sitemap.xml"
[Author]  
  name = "SB"
  
  [Params.sidebar]
 
  # Enable widgets in given order
  widgets = ["search"]
[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
